name: CD Pipeline

on:
  repository_dispatch:
    types: [deploy]

  push:
    tags:
      - 'v*.*.*'

env:
  AWS_REGION: ap-northeast-1
  ECR_REPO: 541320879609.dkr.ecr.ap-northeast-1.amazonaws.com/cicd

################################
# DEV
################################
jobs:
  deploy-dev:
    if: startsWith(github.event.client_payload.branch, 'feature/')
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v3

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to DEV
      run: |
        sed -i "s|image: .*|image: $ECR_REPO@${{ github.event.client_payload.image_digest }}|g" dev/deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Deploy to dev"
        git push

################################
# STAGE
################################
  deploy-stage:
    if: github.event.client_payload.branch == 'main'
    runs-on: ubuntu-latest
    environment: stage

    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to STAGE
      run: |
        sed -i "s|image: .*|image: $ECR_REPO@${{ github.event.client_payload.image_digest }}|g" stage/deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Deploy to stage"
        git push

################################
# UAT (MANUAL APPROVAL)
################################
  deploy-uat:
    if: startsWith(github.event.client_payload.branch, 'release/')
    runs-on: ubuntu-latest
    environment: uat

    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to UAT
      run: |
        sed -i "s|image: .*|image: $ECR_REPO@${{ github.event.client_payload.image_digest }}|g" uat/deployment.yaml
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Deploy to UAT"
        git push

################################
# PROD (TAG + MANUAL APPROVAL)
################################
  deploy-prod:
    if: startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@v3
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to PROD
      run: |
        sed -i "s|image: .*|image: $ECR_REPO@${{ github.event.client_payload.image_digest }}|g" prod/deployment.yaml
