name: CD Pipeline

on:
  repository_dispatch:
    types: [deploy]

jobs:
  cd:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ap-northeast-1

    steps:

    - name: Checkout manifests repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Extract Payload
      run: |
        echo "IMAGE_TAG=${{ github.event.client_payload.image_tag }}" >> $GITHUB_ENV
        echo "BRANCH_NAME=${{ github.event.client_payload.branch }}" >> $GITHUB_ENV

    - name: Determine Target Environment
      run: |
        if [[ "$BRANCH_NAME" == feature/* ]]; then
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "CLUSTER_NAME=eks-dev-cluster" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == main ]]; then
          echo "ENVIRONMENT=stage" >> $GITHUB_ENV
          echo "CLUSTER_NAME=eks-stage-cluster" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == release/* ]]; then
          echo "ENVIRONMENT=uat" >> $GITHUB_ENV
          echo "CLUSTER_NAME=eks-uat-cluster" >> $GITHUB_ENV
        elif [[ "$BRANCH_NAME" == production ]]; then
          echo "ENVIRONMENT=prod" >> $GITHUB_ENV
          echo "CLUSTER_NAME=eks-prod-cluster" >> $GITHUB_ENV
        else
          echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          echo "CLUSTER_NAME=eks-dev-cluster" >> $GITHUB_ENV
        fi

    - name: Update Kubernetes Manifest
      run: |
        FILE="${ENVIRONMENT}/deployment.yaml"
        echo "Updating $FILE with image tag $IMAGE_TAG"
        sed -i "s|image: .*|image: 541320879609.dkr.ecr.ap-northeast-1.amazonaws.com/cicd:${IMAGE_TAG}|g" $FILE

    - name: Commit & Push Updated Manifest
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add .
        git commit -m "Deploy image ${IMAGE_TAG} to ${ENVIRONMENT} environment" || echo "No changes to commit"
        git push https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/abhi10011990/manifests-repo.git

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Update kubeconfig for EKS
      run: |
        aws eks update-kubeconfig \
          --region $AWS_REGION \
          --name $CLUSTER_NAME || echo "Cluster not found, skipping EKS deployment"

    - name: Apply Manifest to Kubernetes
      run: |
        if kubectl config current-context; then
          kubectl apply -f ${ENVIRONMENT}/deployment.yaml
        else
          echo "No cluster context, skipping deployment (use KinD or EKS later)"
        fi
